"""Initial generation

Revision ID: 9e96aa525a41
Revises:
Create Date: 2025-06-16 22:11:47.529156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9e96aa525a41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("date", sa.Date(), nullable=True))
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=mysql.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_index(op.f("username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("username"), "users", ["username"], unique=True)
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.drop_column("expenses", "date")
    # ### end Alembic commands ###
