"""Added payment method in expenses

Revision ID: e3d32062639b
Revises: 9e96aa525a41
Create Date: 2025-06-17 23:04:03.053989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3d32062639b"
down_revision: Union[str, Sequence[str], None] = "9e96aa525a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses", sa.Column("payment_method", sa.String(length=50), nullable=True)
    )
    op.alter_column("expenses", "date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("expenses", "date", existing_type=sa.DATE(), nullable=True)
    op.drop_column("expenses", "payment_method")
    # ### end Alembic commands ###
